---
argument_specs:
  # roles/myapp/tasks/main.yml entry point
  main:
    short_description: Main entry point for the k8s role
    description:
      - This is the main entrypoint for the C(myapp) role.
      - Here we can describe what this entrypoint does in lengthy words.
      - Every new list item is a new paragraph. You can have multiple sentences
        per paragraph.
    author:
      - YukiCS
    options:
      k8s_version:
        type: "str"
        # required: true
        description: "K8s version to compile from source code"

      k8s_build_path:
        type: "str"
        # required: true
        description: "Path to download repo and build Kubernetes source code"

      # myapp_int:
      #   type: "int"
      #   required: false
      #   default: 42
      #   description:
      #     - "The integer value, defaulting to 42."
      #     - "This is a second paragraph."
      # myapp_str:
      #   type: "str"
      #   required: true
      #   description: "The string value"

      # myapp_list:
      #   type: "list"
      #   elements: "str"
      #   required: true
      #   description: "A list of string values."
      #   version_added: 1.3.0

      # myapp_list_with_dicts:
      #   type: "list"
      #   elements: "dict"
      #   required: false
      #   default:
      #     - myapp_food_kind: "meat"
      #       myapp_food_boiling_required: true
      #       myapp_food_preparation_time: 60
      #     - myapp_food_kind: "fruits"
      #       myapp_food_preparation_time: 5
      #   description: "A list of dicts with a defined structure and with default a value."
      #   options:
      #     myapp_food_kind:
      #       type: "str"
      #       choices:
      #         - "vegetables"
      #         - "fruits"
      #         - "grains"
      #         - "meat"
      #       required: false
      #       description: "A string value with a limited list of allowed choices."

      #     myapp_food_boiling_required:
      #       type: "bool"
      #       required: false
      #       default: false
      #       description: "Whether the kind of food requires boiling before consumption."

      #     myapp_food_preparation_time:
      #       type: int
      #       required: true
      #       description: "Time to prepare a dish in minutes."

      # myapp_dict_with_suboptions:
      #   type: "dict"
      #   required: false
      #   default:
      #     myapp_host: "bar.foo"
      #     myapp_exclude_host: true
      #     myapp_path: "/etc/myapp"
      #   description: "A dict with a defined structure and default values."
      #   options:
      #     myapp_host:
      #       type: "str"
      #       choices:
      #         - "foo.bar"
      #         - "bar.foo"
      #         - "ansible.foo.bar"
      #       required: true
      #       description: "A string value with a limited list of allowed choices."

      #     myapp_exclude_host:
      #       type: "bool"
      #       required: true
      #       description: "A boolean value."

      #     myapp_path:
      #       type: "path"
      #       required: true
      #       description: "A path value."

      #     original_name:
      #       type: list
      #       elements: "str"
      #       required: false
      #       description: "An optional list of string values."